In [1]:
import pandas as pd

In [8]:
def extractJobs(path, adjust=0):
    jobs = []
    with open(path) as f:
        data = f.read()[:-1] # do not include "\n"
        for row in data.split("\n"):     # each row in the file
            row_list = row.split(",")    # split each line with ","
            if(len(row_list[0]) != 0):   # if the row has a value
                jobs.append(row_list[1+adjust]) # append the job to jobs list
    return jobs[1-adjust:]

def oldJobs(path,adjust=1):

    with open(path,'w+') as f:
        read_char = f.read(1)
        
        if (not read_char):
            return []
    return extractJobs(path,adjust)

def register(df,old_jobs):
    for i in range(len(df)):
        df["Ticket"] = df.iloc[i]["Name"] in old_jobs # save False if no record of this job found

    return df

def merge(paths):
    jobs = []

    for i in paths:
        jobs += extractJobs(i)

    return [i for i in jobs if (len(i) != 0)]

def concat_df(paths, old_jobs):

    df = pd.DataFrame()

    for path in paths:
        df_i = pd.read_csv(path)
        df_i = register(df_i, old_jobs)
        df = pd.concat([df,df_i],ignore_index=True)
    
    return df

In [3]:
old_path = "csv/jobs.csv"
paths = ["csv/coderspace.csv","csv/tcmb.csv"]

In [16]:
new_jobs = merge(paths)

In [20]:
old_jobs = oldJobs(old_path)

In [21]:
df = concat_df(paths, old_jobs)

In [22]:
df

,Type,Name,Status,Date,Site,Ticket
0,Hiring Challenge,Türkiye Sigorta Hiring Challenge #3,True,8 Haziran,Coderspace,False
1,Hackathon-Datathon,Bursa Akıllı Şehir Deprem Hackathonu,True,11 Haziran,Coderspace,False
2,Meet-up,Product Management Camp,True,13 Haziran,Coderspace,False
3,Yetenek Programı,Sabancı SEED Digital Genç Yetenek İşe Alım Pro...,False,23 Nisan,Coderspace,False
4,Bootcamp,Akbank & Microsoft AI Academy Data Analyst Eği...,False,15 Mart,Coderspace,False
5,Hackathon-Datathon,Shell Datathon 2023,False,16 Mayıs,Coderspace,False
6,Yetenek Programı,Softtech Yetenek Kuşağı,False,28 Mayıs,Coderspace,False
7,BT Müfettiş Yardımcısı Olarak Görev Yapmak Üze...,BT Müfettiş Yardımcısı,False,18/05/2023,TCMB,False
8,Bilişim Uzman Yardımcısı Olarak Görev Yapmak Ü...,Bilişim Uzman Yardımcısı,False,18/05/2023,TCMB,False
9,Türkiye Cumhuriyet Merkez Bankasına Çevirmen A...,NaN,False,18/05/2023,TCMB,False

In [ ]:
df.to_csv("csv/jobs.csv")